# Generated by Django 4.2.1 on 2023-06-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0008_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='image',
            field=models.ImageField(default=2, upload_to='./static/Image/uploads/cart_images/'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='cart',
            table='list_cart_products',
        ),
    ]
